export const MAX_GUESSES = 10

export const REGEX = /^[a-zA-Z]+$/;

// POINTS FOR CORRECT LETTER
export const EASY_CORRECT_LETTER = 10
export const MEDIUM_CORRECT_LETTER = 15
export const HARD_CORRECT_LETTER = 20

// POINTS DEDUCTED FOR INCORRECT LETTERS
export const EASY_INCORRECT_LETTER = 2
export const MEDIUM_INCORRECT_LETTER = 4
export const HARD_INCORRECT_LETTER = 6

// POINTS FOR GETTING THE WORD
export const EASY_WORD_GUESSED = 20
export const MEDIUM_WORD_GUESSED = 30
export const HARD_WORD_GUESSED = 40

// POINTS DEDUCTED FOR NOT GETTING THE WORD
export const EASY_WORD_NOT_GUESSED = 10
export const MEDIUM_WORD_NOT_GUESSED = 15
export const HARD_WORD_NOT_GUESSED = 20

